### ISSUE TITLE
detailed mode & definition search aren't saved to localStorage

### ISSUE THREAD

**Issue by ILikeTrains27** [lipu-linku/lipu-linku.github.io#20]
The states of the detailed mode & definition search checkboxes aren't preserved when you reload the page.

This is because they don't have default values, and only the checkboxes that have default values get stored to localStorage, so I think you should make them have default values.

In line 616 of scripts.js, a comment says "do not save, user consideration", idk what that means, it also says it's like this because otherwise it's laggy, but I ran it on my computer and I don't think it's laggy.

**Comment by gregdan3** [comment]
- The definition search is intentionally not saved to localStorage because the primary purpose of the dictionary is to search by word, not by definition- saving the definition search setting would be a repeated gotcha as you open and close the dictionary and have to manually choose to disable, when most users are searching for a word they already know. This version where we do not preserve the setting was the closest I could get to a best of both worlds situation, under the assumption that even a user who does use the definition search would more often want to search words instead of definitions upon newly opening the dictionary.
- The lag I mention there primarily applies primarily to mobile, but it probably is not as bad as I remember it being. That said, with similar reasoning, we do not want to save the detailed mode to localStorage unless it were shown in the UI in a de-emphasized way or it were less expensive to re-sort the list of words on mobile. For what it's worth, mobile experiences noticeable if small freezes when emptying the search bar or typing a single letter into it, which are more noticeable when detailed mode is turned on.

**Comment by gregdan3** [comment]
^ as an aside to this, I would like to not even have a detailed mode option if we were to re-do the frontend with a framework or something to improve the current design. It should just be accessible on the page without thinking about it.
